service: cumulus-workflow-engine # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "datapipeline:*"
        - "dynamodb:*"
        - "iam:PassRole"
      Resource:
        - "*"

plugins:
  - serverless-offline

functions:

  # stats summary
  statsSummary:
    handler: handler.statsSummary
    timeout: 300
    events:
      - http:
          path: stats/summary
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # stats summary grouped
  statsSummaryGrouped:
    handler: handler.statsSummaryGrouped
    timeout: 300
    events:
      - http:
          path: stats/summary/grouped
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # get error stats
  getErrorCounts:
    handler: handler.getErrorCounts
    timeout: 300
    events:
      - http:
          path: stats/errors
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # get list of errors
  listErrors:
    handler: handler.listErrors
    timeout: 300
    events:
      - http:
          path: errors
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # list all granules
  listGranules:
    handler: handler.listGranules
    timeout: 300
    events:
      - http:
          path: granules/{dataSet}
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  getGranules:
    handler: handler.getGranules
    timeout: 300
    events:
      - http:
          path: granules/{dataSet}/{granuleName}
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # list all dataset records
  listDataSet:
    handler: handler.listDataSets
    timeout: 300
    events:
      - http:
          path: datasets
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # get a particular dataset
  getDataSet:
    handler: handler.getDataSet
    timeout: 300
    events:
      - http:
          path: datasets/{short_name}
          method: get
          private: true
          cors: true

  # post a new dataSet record
  postDataSet:
    handler: handler.postDataSet
    timeout: 300
    events:
      - http:
          path: datasets
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            id: 68s1ev
          cors: true

  # trigger lambda
  trigger:
    handler: handler.trigger
