service: cumulus-workflow-engine # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

functions:

  listDataSet:
    handler: handler.listDataSets

#   you can add any of the following events
    events:
      - http:
          path: datasets
          method: get

  getDataSet:
    handler: handler.getDataSet

#   you can add any of the following events
    events:
      - http:
          path: datasets/{short_name}
          method: get

