service: cumulus-workflow-engine # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

functions:

  # list all dataset records
  listDataSet:
    handler: handler.listDataSets
    events:
      - http:
          path: datasets
          method: get

  # get a particular dataset
  getDataSet:
    handler: handler.getDataSet
    events:
      - http:
          path: datasets/{short_name}
          method: get

  # post a new dataSet record
  postDataSet:
    handler: handler.postDataSet
    events:
      - http:
          path: datasets
          method: post
