version: 2
jobs:
  build:
    docker:
      - image: node:4.8.0-wheezy
      - image: peopleperhour/dynamodb
      - image: vsouza/sqs-local
      - image: elasticsearch:2.3.5
    working_directory: ~/cumulus-api
    steps:
      - checkout
      # ... steps for building/testing app ...

      - run:
          name: Installing Dependencies
          command: npm install

      # build and push Docker image
      - run:
          name: Running Test
          command: |
            cp config/secrets.json.example config/secrets.json
            npm run test
