stackName: cumulus-api
stage: dev
configBucket: cumulus-private
buildApiGateway: true
lambdas:
  - name: signup
    handler: handlers/auth.signup
    timeout: 300
    apiGateway:
      path: signup
      method: post
      cors: trues

  - name: signin
    handler: handlers/auth.signin
    timeout: 300
    apiGateway:
      path: signin
      method: post
      cors: true

  - name: statsSummary
    handler: handlers/stats.summary
    timeout: 300
    apiGateway:
      path: stats/summary
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: statsSummaryGrouped
    handler: handlers/stats.summaryGrouped
    timeout: 300
    apiGateway:
      path: stats/summary/grouped
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: getErrorCounts
    handler: handlers/errors.counts
    timeout: 300
    apiGateway:
      path: stats/errors
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: listErrors
    handler: handlers/errors.list
    timeout: 300
    apiGateway:
      path: errors
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: listGranules
    handler: handlers/granules.list
    timeout: 300
    apiGateway:
      path: granules/{collection}
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: getGranules
    handler: handlers/granules.get
    timeout: 300
    apiGateway:
      path: granules/{collection}/{granuleName}
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: listCollections
    handler: handlers/collections.list
    timeout: 300
    apiGateway:
      path: collections
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: getCollection
    handler: handlers/collections.get
    timeout: 300
    apiGateway:
      path: collections/{short_name}
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: postCollection
    handler: handlers/collections.post
    timeout: 300
    apiGateway:
      path: collections
      method: post
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: putCollection
    handler: handlers/collections.put
    timeout: 300
    apiGateway:
      path: collections
      method: put
      authorizer:
        type: COGNITO_USER_POOLS
        id: b961m7
      cors: true

  - name: trigger
    handler: handlers/triggers.trigger
    timeout: 300
